// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/serg1732/practicum-first-coursework/internal/model"

	slog "log/slog"
)

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, log, authorization
func (_m *AccountRepository) Create(ctx context.Context, log *slog.Logger, authorization *model.Accounts) error {
	ret := _m.Called(ctx, log, authorization)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *slog.Logger, *model.Accounts) error); ok {
		r0 = rf(ctx, log, authorization)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: ctx, log, auth
func (_m *AccountRepository) Login(ctx context.Context, log *slog.Logger, auth *model.Accounts) (*int64, error) {
	ret := _m.Called(ctx, log, auth)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slog.Logger, *model.Accounts) (*int64, error)); ok {
		return rf(ctx, log, auth)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slog.Logger, *model.Accounts) *int64); ok {
		r0 = rf(ctx, log, auth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slog.Logger, *model.Accounts) error); ok {
		r1 = rf(ctx, log, auth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccountRepository creates a new instance of AccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRepository {
	mock := &AccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
