// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/serg1732/practicum-first-coursework/internal/model"

	slog "log/slog"
)

// BalanceRepository is an autogenerated mock type for the BalanceRepository type
type BalanceRepository struct {
	mock.Mock
}

// GetBalance provides a mock function with given fields: ctx, log, accountId
func (_m *BalanceRepository) GetBalance(ctx context.Context, log *slog.Logger, accountId int64) (*model.BalanceDB, error) {
	ret := _m.Called(ctx, log, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *model.BalanceDB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slog.Logger, int64) (*model.BalanceDB, error)); ok {
		return rf(ctx, log, accountId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slog.Logger, int64) *model.BalanceDB); ok {
		r0 = rf(ctx, log, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BalanceDB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slog.Logger, int64) error); ok {
		r1 = rf(ctx, log, accountId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetForUpdate provides a mock function with given fields: ctx, log, accountId, sum
func (_m *BalanceRepository) GetForUpdate(ctx context.Context, log *slog.Logger, accountId int64, sum float64) (bool, error) {
	ret := _m.Called(ctx, log, accountId, sum)

	if len(ret) == 0 {
		panic("no return value specified for GetForUpdate")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slog.Logger, int64, float64) (bool, error)); ok {
		return rf(ctx, log, accountId, sum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slog.Logger, int64, float64) bool); ok {
		r0 = rf(ctx, log, accountId, sum)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slog.Logger, int64, float64) error); ok {
		r1 = rf(ctx, log, accountId, sum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBalanceRepository creates a new instance of BalanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceRepository {
	mock := &BalanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
