// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/serg1732/practicum-first-coursework/internal/model"

	slog "log/slog"
)

// WithdrawsRepository is an autogenerated mock type for the WithdrawsRepository type
type WithdrawsRepository struct {
	mock.Mock
}

// AddWithdraw provides a mock function with given fields: ctx, log, accountId, withdraw
func (_m *WithdrawsRepository) AddWithdraw(ctx context.Context, log *slog.Logger, accountId int64, withdraw *model.WithdrawRequest) error {
	ret := _m.Called(ctx, log, accountId, withdraw)

	if len(ret) == 0 {
		panic("no return value specified for AddWithdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *slog.Logger, int64, *model.WithdrawRequest) error); ok {
		r0 = rf(ctx, log, accountId, withdraw)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWithdrawals provides a mock function with given fields: ctx, log, accountId
func (_m *WithdrawsRepository) GetWithdrawals(ctx context.Context, log *slog.Logger, accountId int64) ([]*model.Withdrawals, error) {
	ret := _m.Called(ctx, log, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []*model.Withdrawals
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *slog.Logger, int64) ([]*model.Withdrawals, error)); ok {
		return rf(ctx, log, accountId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *slog.Logger, int64) []*model.Withdrawals); ok {
		r0 = rf(ctx, log, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Withdrawals)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *slog.Logger, int64) error); ok {
		r1 = rf(ctx, log, accountId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWithdrawsRepository creates a new instance of WithdrawsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithdrawsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithdrawsRepository {
	mock := &WithdrawsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
