// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/serg1732/practicum-first-coursework/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// AccrualClient is an autogenerated mock type for the AccrualClient type
type AccrualClient struct {
	mock.Mock
}

// GetOrdersAccrual provides a mock function with given fields: orderId
func (_m *AccrualClient) GetOrdersAccrual(orderId string) (*model.AccrualResponse, *int, error) {
	ret := _m.Called(orderId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersAccrual")
	}

	var r0 *model.AccrualResponse
	var r1 *int
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (*model.AccrualResponse, *int, error)); ok {
		return rf(orderId)
	}
	if rf, ok := ret.Get(0).(func(string) *model.AccrualResponse); ok {
		r0 = rf(orderId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccrualResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *int); ok {
		r1 = rf(orderId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*int)
		}
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(orderId)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewAccrualClient creates a new instance of AccrualClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccrualClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccrualClient {
	mock := &AccrualClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
