// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/serg1732/practicum-first-coursework/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// AccuralClient is an autogenerated mock type for the AccuralClient type
type AccuralClient struct {
	mock.Mock
}

type AccuralClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AccuralClient) EXPECT() *AccuralClient_Expecter {
	return &AccuralClient_Expecter{mock: &_m.Mock}
}

// GetOrdersAccrual provides a mock function with given fields: orderId
func (_m *AccuralClient) GetOrdersAccrual(orderId string) (*model.AccrualResponse, *int, error) {
	ret := _m.Called(orderId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersAccrual")
	}

	var r0 *model.AccrualResponse
	var r1 *int
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (*model.AccrualResponse, *int, error)); ok {
		return rf(orderId)
	}
	if rf, ok := ret.Get(0).(func(string) *model.AccrualResponse); ok {
		r0 = rf(orderId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccrualResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *int); ok {
		r1 = rf(orderId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*int)
		}
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(orderId)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AccuralClient_GetOrdersAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrdersAccrual'
type AccuralClient_GetOrdersAccrual_Call struct {
	*mock.Call
}

// GetOrdersAccrual is a helper method to define mock.On call
//   - orderId string
func (_e *AccuralClient_Expecter) GetOrdersAccrual(orderId interface{}) *AccuralClient_GetOrdersAccrual_Call {
	return &AccuralClient_GetOrdersAccrual_Call{Call: _e.mock.On("GetOrdersAccrual", orderId)}
}

func (_c *AccuralClient_GetOrdersAccrual_Call) Run(run func(orderId string)) *AccuralClient_GetOrdersAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AccuralClient_GetOrdersAccrual_Call) Return(_a0 *model.AccrualResponse, _a1 *int, _a2 error) *AccuralClient_GetOrdersAccrual_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *AccuralClient_GetOrdersAccrual_Call) RunAndReturn(run func(string) (*model.AccrualResponse, *int, error)) *AccuralClient_GetOrdersAccrual_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccuralClient creates a new instance of AccuralClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccuralClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccuralClient {
	mock := &AccuralClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
